-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EditoraDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EditoraDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EditoraDB` DEFAULT CHARACTER SET utf8 ;
USE `EditoraDB` ;

-- -----------------------------------------------------
-- Table `EditoraDB`.`EXEMPLAR_STATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`EXEMPLAR_STATUS` (
  `IDEXEMPLAR` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `DESC` VARCHAR(200) NULL,
  PRIMARY KEY (`IDEXEMPLAR`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`EXEMPLAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`EXEMPLAR` (
  `idEXEMPLAR` INT NOT NULL AUTO_INCREMENT,
  `LOCALIZACAO` VARCHAR(45) NOT NULL,
  `EXEMPLAR_STATUS_IDEXEMPLAR` INT NOT NULL,
  PRIMARY KEY (`idEXEMPLAR`),
  INDEX `fk_EXEMPLAR_EXEMPLAR_STATUS1_idx` (`EXEMPLAR_STATUS_IDEXEMPLAR` ASC),
  CONSTRAINT `fk_EXEMPLAR_EXEMPLAR_STATUS1`
    FOREIGN KEY (`EXEMPLAR_STATUS_IDEXEMPLAR`)
    REFERENCES `EditoraDB`.`EXEMPLAR_STATUS` (`IDEXEMPLAR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`AUTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`AUTOR` (
  `idAUTOR` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `BIOGRAFIA` VARCHAR(1000) NOT NULL,
  `DATA_DE_NASCIMENTO` DATE NOT NULL,
  `NACIONALIDADE` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idAUTOR`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`AREA_DE_CONHECIMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`AREA_DE_CONHECIMENTO` (
  `idAREA_DE_CONHECIMENTO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `DESCRICAO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idAREA_DE_CONHECIMENTO`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`LIVRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`LIVRO` (
  `idLIVRO` INT NOT NULL AUTO_INCREMENT,
  `ISBN` VARCHAR(13) NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `SINOPSE` VARCHAR(500) NULL,
  `NUMERO_DE_PAGINAS` INT NOT NULL,
  `DATA_DE_PUBLICACAO` DATE NOT NULL,
  `EXEMPLAR_idEXEMPLAR` INT NOT NULL,
  `AUTOR_idAUTOR` INT NOT NULL,
  `AREA_DE_CONHECIMENTO_idAREA_DE_CONHECIMENTO` INT NOT NULL,
  PRIMARY KEY (`idLIVRO`),
  INDEX `fk_LIVRO_EXEMPLAR1_idx` (`EXEMPLAR_idEXEMPLAR` ASC),
  INDEX `fk_LIVRO_AUTOR1_idx` (`AUTOR_idAUTOR` ASC),
  INDEX `fk_LIVRO_AREA_DE_CONHECIMENTO1_idx` (`AREA_DE_CONHECIMENTO_idAREA_DE_CONHECIMENTO` ASC),
  CONSTRAINT `fk_LIVRO_EXEMPLAR1`
    FOREIGN KEY (`EXEMPLAR_idEXEMPLAR`)
    REFERENCES `EditoraDB`.`EXEMPLAR` (`idEXEMPLAR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIVRO_AUTOR1`
    FOREIGN KEY (`AUTOR_idAUTOR`)
    REFERENCES `EditoraDB`.`AUTOR` (`idAUTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIVRO_AREA_DE_CONHECIMENTO1`
    FOREIGN KEY (`AREA_DE_CONHECIMENTO_idAREA_DE_CONHECIMENTO`)
    REFERENCES `EditoraDB`.`AREA_DE_CONHECIMENTO` (`idAREA_DE_CONHECIMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`PALAVRA_CHAVE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`PALAVRA_CHAVE` (
  `idPALAVRA CHAVE` INT NOT NULL AUTO_INCREMENT,
  `NOME_PALAVRA_CHAVE` VARCHAR(45) NOT NULL,
  `DESCRICAO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPALAVRA CHAVE`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`PEDIDO_STATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`PEDIDO_STATUS` (
  `IDSTATUS` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `DESC` VARCHAR(200) NULL,
  PRIMARY KEY (`IDSTATUS`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`PEDIDO` (
  `idPEDIDO` INT NOT NULL AUTO_INCREMENT,
  `DATAPEDIDO` DATE NOT NULL,
  `PEDIDO_STATUS_IDSTATUS` INT NOT NULL,
  PRIMARY KEY (`idPEDIDO`),
  INDEX `fk_PEDIDO_PEDIDO_STATUS1_idx` (`PEDIDO_STATUS_IDSTATUS` ASC),
  CONSTRAINT `fk_PEDIDO_PEDIDO_STATUS1`
    FOREIGN KEY (`PEDIDO_STATUS_IDSTATUS`)
    REFERENCES `EditoraDB`.`PEDIDO_STATUS` (`IDSTATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`TIPO_DE_PAGAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`TIPO_DE_PAGAMENTO` (
  `idTIPO_DE_PAGAMENTO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `TAXA` VARCHAR(45) NOT NULL,
  `TAXA_DE_COMPENSACAO` VARCHAR(45) NOT NULL,
  `DESCRICAO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idTIPO_DE_PAGAMENTO`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`CARGO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`CARGO` (
  `idCARGO` INT NOT NULL AUTO_INCREMENT,
  `NOMECARGO` VARCHAR(45) NOT NULL,
  `DESCCARGO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCARGO`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`DEPARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`DEPARTAMENTO` (
  `idDEPARTAMENTO` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  `DESCRICAO` VARCHAR(300) NOT NULL,
  `FUNCIONARIO_CPF` VARCHAR(14) NULL,
  PRIMARY KEY (`idDEPARTAMENTO`),
  INDEX `fk_DEPARTAMENTO_FUNCIONARIO1_idx` (`FUNCIONARIO_CPF` ASC),
  CONSTRAINT `fk_RESPONSAVEL`
    FOREIGN KEY (`FUNCIONARIO_CPF`)
    REFERENCES `EditoraDB`.`FUNCIONARIO` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`FUNCIONARIO` (
  `CPF` VARCHAR(14) NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `TELEFONE` VARCHAR(15) NOT NULL,
  `EMAIL` VARCHAR(60) NOT NULL UNIQUE,
  `CARGO_idCARGO` INT NOT NULL,
  `DEPARTAMENTO_idDEPARTAMENTO` INT NOT NULL,
  PRIMARY KEY (`CPF`),
  INDEX `fk_FUNCIONARIO_CARGO1_idx` (`CARGO_idCARGO` ASC),
  INDEX `fk_FUNCIONARIO_DEPARTAMENTO1_idx` (`DEPARTAMENTO_idDEPARTAMENTO` ASC),
  CONSTRAINT `fk_FUNCIONARIO_CARGO1`
    FOREIGN KEY (`CARGO_idCARGO`)
    REFERENCES `EditoraDB`.`CARGO` (`idCARGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FUNCIONARIO_DEPARTAMENTO1`
    FOREIGN KEY (`DEPARTAMENTO_idDEPARTAMENTO`)
    REFERENCES `EditoraDB`.`DEPARTAMENTO` (`idDEPARTAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`VENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`VENDA` (
  `idVENDA` INT NOT NULL AUTO_INCREMENT,
  `DATAVENDA` DATE NOT NULL,
  `VALOR` DECIMAL(6,2) NOT NULL,
  `TIPO_DE_PAGAMENTO_idTIPO_DE_PAGAMENTO` INT NOT NULL,
  `FUNCIONARIO_CPF` VARCHAR(14) NOT NULL,
  `PEDIDO_idPEDIDO` INT NOT NULL,
  PRIMARY KEY (`idVENDA`),
  INDEX `fk_VENDA_TIPO_DE_PAGAMENTO1_idx` (`TIPO_DE_PAGAMENTO_idTIPO_DE_PAGAMENTO` ASC),
  INDEX `fk_VENDA_FUNCIONARIO1_idx` (`FUNCIONARIO_CPF` ASC),
  INDEX `fk_VENDA_PEDIDO1_idx` (`PEDIDO_idPEDIDO` ASC),
  CONSTRAINT `fk_VENDA_TIPO_DE_PAGAMENTO1`
    FOREIGN KEY (`TIPO_DE_PAGAMENTO_idTIPO_DE_PAGAMENTO`)
    REFERENCES `EditoraDB`.`TIPO_DE_PAGAMENTO` (`idTIPO_DE_PAGAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENDA_FUNCIONARIO1`
    FOREIGN KEY (`FUNCIONARIO_CPF`)
    REFERENCES `EditoraDB`.`FUNCIONARIO` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENDA_PEDIDO1`
    FOREIGN KEY (`PEDIDO_idPEDIDO`)
    REFERENCES `EditoraDB`.`PEDIDO` (`idPEDIDO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`FERIAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`FERIAS` (
  `DATAINICIO` DATE NOT NULL,
  `DATAVOLTA` DATE NOT NULL,
  `DURACAO` INT NULL,
  `FUNCIONARIO_CPF` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`FUNCIONARIO_CPF`),
  CONSTRAINT `fk_FERIAS_FUNCIONARIO1`
    FOREIGN KEY (`FUNCIONARIO_CPF`)
    REFERENCES `EditoraDB`.`FUNCIONARIO` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`DEPENDENTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`DEPENDENTES` (
  `CPF` VARCHAR(14) NOT NULL,
  `DATANASCIMENTO` DATE NOT NULL,
  `PARENTESCO` VARCHAR(45) NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `FUNCIONARIO_CPF` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`CPF`),
  INDEX `fk_DEPENDENTES_FUNCIONARIO1_idx` (`FUNCIONARIO_CPF` ASC),
  CONSTRAINT `fk_DEPENDENTES_FUNCIONARIO1`
    FOREIGN KEY (`FUNCIONARIO_CPF`)
    REFERENCES `EditoraDB`.`FUNCIONARIO` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`GENERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`GENERO` (
  `idGENERO` INT NOT NULL AUTO_INCREMENT,
  `NOMEGENERO` VARCHAR(45) NOT NULL,
  `DESCGENERO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idGENERO`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`ENDERECO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`ENDERECO` (
  `CEP` CHAR(8) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  `BAIRRO` VARCHAR(45) NOT NULL,
  `CIDADE` VARCHAR(45) NOT NULL,
  `RUA` VARCHAR(45) NOT NULL,
  `NUMERO` VARCHAR(10) NOT NULL,
  `COMPLEMENTO` VARCHAR(45) NULL,
  `REFERENCIA` VARCHAR(45) NULL,
  `FUNCIONARIO_CPF` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`FUNCIONARIO_CPF`),
  CONSTRAINT `fk_ENDERECO_FUNCIONARIO`
    FOREIGN KEY (`FUNCIONARIO_CPF`)
    REFERENCES `EditoraDB`.`FUNCIONARIO` (`CPF`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`LIVRO_PALAVRA_CHAVE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`LIVRO_PALAVRA_CHAVE` (
  `LIVRO_idLIVRO` INT NOT NULL,
  `PALAVRA_CHAVE_idPALAVRA CHAVE` INT NOT NULL,
  PRIMARY KEY (`LIVRO_idLIVRO`, `PALAVRA_CHAVE_idPALAVRA CHAVE`),
  INDEX `fk_LIVRO_PALAVRA_CHAVE_PALAVRA_CHAVE1_idx` (`PALAVRA_CHAVE_idPALAVRA CHAVE` ASC),
  CONSTRAINT `fk_LIVRO_PALAVRA_CHAVE_LIVRO1`
    FOREIGN KEY (`LIVRO_idLIVRO`)
    REFERENCES `EditoraDB`.`LIVRO` (`idLIVRO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LIVRO_PALAVRA_CHAVE_PALAVRA_CHAVE1`
    FOREIGN KEY (`PALAVRA_CHAVE_idPALAVRA CHAVE`)
    REFERENCES `EditoraDB`.`PALAVRA_CHAVE` (`idPALAVRA CHAVE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`LIVRO_GENERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`LIVRO_GENERO` (
  `GENERO_idGENERO` INT NOT NULL,
  `LIVRO_idLIVRO` INT NOT NULL,
  INDEX `fk_LIVRO_GENERO_GENERO1_idx` (`GENERO_idGENERO` ASC),
  PRIMARY KEY (`LIVRO_idLIVRO`, `GENERO_idGENERO`),
  CONSTRAINT `fk_LIVRO_GENERO_GENERO1`
    FOREIGN KEY (`GENERO_idGENERO`)
    REFERENCES `EditoraDB`.`GENERO` (`idGENERO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIVRO_GENERO_LIVRO1`
    FOREIGN KEY (`LIVRO_idLIVRO`)
    REFERENCES `EditoraDB`.`LIVRO` (`idLIVRO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `EditoraDB`.`LIVRO_PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EditoraDB`.`LIVRO_PEDIDO` (
  `LIVRO_idLIVRO` INT NOT NULL,
  `PEDIDO_idPEDIDO` INT NOT NULL,
  PRIMARY KEY (`LIVRO_idLIVRO`, `PEDIDO_idPEDIDO`),
  INDEX `fk_LIVRO_has_PEDIDO_PEDIDO1_idx` (`PEDIDO_idPEDIDO` ASC),
  INDEX `fk_LIVRO_has_PEDIDO_LIVRO1_idx` (`LIVRO_idLIVRO` ASC),
  CONSTRAINT `fk_LIVRO_has_PEDIDO_LIVRO1`
    FOREIGN KEY (`LIVRO_idLIVRO`)
    REFERENCES `EditoraDB`.`LIVRO` (`idLIVRO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_LIVRO_has_PEDIDO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_idPEDIDO`)
    REFERENCES `EditoraDB`.`PEDIDO` (`idPEDIDO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
